# TENT on Semantic FPN R-50 source.
_BASE_: "../Cityscapes/semantic_R_50_FPN_singletask.yaml"
MODEL:
  META_ARCHITECTURE: "TENT_SemSeg"
  WEIGHTS: "/workspace/output/semantic_R50_cityscapes/model_final.pth"

INPUT:
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048

DATASETS:
  TEST: ("acdc_fog_semseg", "acdc_night_semseg", "acdc_rain_semseg", "acdc_snow_semseg")

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  STEPS: ()
  MAX_ITER: 400
  WARMUP_ITERS: 0

OUTPUT_DIR: "/workspace/output/tent_semseg_R50_C2ACDC"
